config/urls.py
from django.contrib import admin
from django.urls import path


from barcode_server.views import login_view, register_user, index, user_page, logout_view, dashboard

urlpatterns = [
    path('admin/', admin.site.urls),
    # The home page
    path('', index, name='home'),
    path('dashboard/', dashboard, name='dashboard'),
    path('user/', user_page, name='user_page'),
    path("login/", login_view, name="login"),
    path("register/", register_user, name="register"),
    path("logout/", logout_view, name="logout")
]

barcode_server/models.py
"""
This is Models in Barcode Server!

If you update or refactoring about database, Rewrite this!
"""
from django.db import models
from django.contrib.auth.models import User as U

# Create your models here.


class User(models.Model):
    '''
    Title : User

    This is User table extends admin user in django

    Attributes:
        user (Djang admin User) : This is One To One Filed to connect user in django
    '''
    user = models.OneToOneField(U, on_delete=models.CASCADE)


class Result(models.Model):
    '''
    Title : Result

    This is Result of recogniztion image

    Attributes:
        user (Djang admin User) : This is One To One Filed our user
        recognized (boolean) : This is boolean about recognition
        udi (string) : This is UDi barcode data
        img_path (string) : THis is img path
    '''
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    dates = models.DateTimeField(auto_now_add=True)
    recognized = models.BooleanField(default=False)
    udi = models.CharField(max_length=300, default="NOT FOUND")
    img_path = models.CharField(max_length=300, null=True)

barcode_server/forms.py
"""
This is forms module!

What i use in templates for form, in here!
"""
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class LoginForm(forms.Form):
    '''
    Title : LoginForm

    This form is used in login templates

    Attributes:
        username (string) : this is marked with class form-control
        password (string) : this is marked with class form-control
    '''
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "Username",
                "class": "form-control"
            }
        ))
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Password",
                "class": "form-control"
            }
        ))


class SignUpForm(UserCreationForm):
    '''
    Title : SignUpForm

    This form is used in register templates

    Attributes:
        username (string) : this is marked with class form-control
        email (string) : this is marked with class form-control
        password1 (string) : this is marked with class form-control
        password2 (string) : this is marked with class form-control

        meta (admin_user)
            fields = ('username', 'email', 'password1', 'password2')
    '''
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "Username",
                "class": "form-control"
            }
        ))
    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={
                "placeholder": "Email",
                "class": "form-control"
            }
        ))
    password1 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Password",
                "class": "form-control"
            }
        ))
    password2 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Password check",
                "class": "form-control"
            }
        ))

    class Meta:
        """
        This is meta class for matching form data with admin user model!
        """
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class UploadFileForm(forms.Form):
    '''
    Title : UploadFileForm

    This form is used in index templates to upload barcode image

    Attributes:
        file (file) : this is file field
    '''
    file = forms.FileField()

barcode_server/views.py
"""
This is Views(business logic) in Barcode_server
"""
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core.files.storage import default_storage
from django.core.files.base import ContentFile

from barcode_server.forms import LoginForm, SignUpForm, UploadFileForm
from barcode_server.models import Result, User
from barcode_server.service.barcode_service import BarcodeService

# Create your views here.


@login_required(login_url="/login/")
def index(request):
    '''
    Title : index

    This is index, main page view

    This page do recognize barcode logic

    return:
        GET : return home/index.html
        POST : return home/index.html with result
    '''
    context = {'segment': 'index'}
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            f = request.FILES["file"]
            user_one = User.objects.filter(user_id=request.user.id).first()
            path = default_storage.save('static/media/barcode.jpeg', ContentFile(f.read()))
            barcodeService = BarcodeService()
            msg = barcodeService.uploadSerivce(path)
            result = Result(user=user_one,recognized=msg.get("msg"),udi=msg.get("data"),img_path="/"+path)
            result.save()
            context["msg"] = msg.get("msg")
            context["data"] = msg.get("data")
            return render(request, 'home/index.html', context)
    else:
        form = UploadFileForm()
    return render(request, 'home/index.html', context)


@login_required(login_url="/login/")
def dashboard(request):
    '''
    Title : dashboard

    This is dashboard view

    This page return histories

    return:
        All : return home/dashboard.html
    '''
    results = Result.objects.filter(user_id = request.user.id).all().order_by('-dates')[:10]
    context = {'segment': 'dashboard', "results" : results}
    return render(request, 'home/dashboard.html', context)


@login_required(login_url="/login/")
def user_page(request):
    '''
    TODO : Add update user date form!

    Title : user_page

    This is user_page view

    This page return user data

    return:
        All : return home/page-user.html
    '''
    context = {'segment': 'user'}
    return render(request, 'home/page-user.html', context)

def login_view(request):
    '''
    Title : login_view

    This is login view

    It has login form to login logic

    return:
        GET : return home/dashboard.html
        POST : return home/dashboard.html with result of login
    '''
    form = LoginForm(request.POST or None)
    msg = None
    if request.method == "POST":
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect("/")
            msg = 'Invalid credentials'
        else:
            msg = 'Error validating the form'
    return render(request, "accounts/login.html", {"form": form, "msg": msg})


def register_user(request):
    '''
    Title : register_user

    This is register view

    It has register form to register logic

    return:
        GET : return accounts/register.html
        POST :
            if sueccess :
                redirect "/"
            else :
                return accounts/register.html with fail
    '''
    msg = None
    success = False
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            admin_user=form.save()
            user = User(user=admin_user)
            user.save()
            username = form.cleaned_data.get("username")
            raw_password = form.cleaned_data.get("password1")
            authenticate(username=username, password=raw_password)
            msg = 'User created - please <a href="/login">login</a>.'
            success = True
        else:
            msg = 'Form is not valid'
    else:
        form = SignUpForm()
    return render(request, "accounts/register.html", {"form": form, "msg": msg, "success": success})


def logout_view(request):
    '''
    Title : logout_view

    This is logout view

    return:
        All : redirect login page
    '''
    logout(request)
    return redirect("login")

templates/accounts/login.html
{% extends "layouts/base.html" %}

{% block title %} Login {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

        <div class="row login-card ">
          <div class="col-md-8">
            <div class="card">
              <form role="form" method="post" action="">
              
                {% csrf_token %} 

                <div class="card-header">
                  <h5 class="title">Login</h5>

                  <h6 class="card-category">
                      {% if msg %}
                        <span class="text-danger">{{ msg }}</span>
                      {% else %}
                        Add your credentials
                      {% endif %}  
                  </h6>
                </div>

                <div class="login-card-body">
                  <div class = "card-body-left">
                    <img class = "login-img" id = "login-img" src="/static/logo.png" alt="Profile Photo"> 
                  </div>
                  <div class = "card-body-right">
                    <div class="login-input-div">
                      <div class="px-md-1">
                        <div class="form-group">
                          <label>Username</label>
                          {{ form.username }}
                        </div>
                      </div>
                    </div>
                    <div class="login-input-div">
                      <div class="px-md-1">
                        <div class="form-group">
                          <label>Password</label>
                          {{ form.password }}
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="login-card-footer">
                  <div class = "login-footer-item">
                    &nbsp; &nbsp;
                    Don't have an account? <a href="/register" class="text-primary">Create</a>
                  </div>
                  <button type="submit" name="login" class="btn btn-fill login-footer-item">Login</button>
                </div>
              </form>

            </div>
          </div>
      </div>


{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

templates/accounts/register.html
{% extends "layouts/base.html" %}

{% block title %} Register {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

        <div class="row">
          <div class="col-md-8">
            <div class="card">

              <form role="form" method="post" action="">
              
                {% csrf_token %} 

                <div class="card-header">
                  <h5 class="title">Register</h5>

                  <h6 class="card-category">
                      {% if msg %}
                        <span class="text-danger">{{ msg | safe }}</span>
                      {% else %}
                        Add your credentials
                      {% endif %}  
                  </h6>
                </div>

              {% if success %}

                <p>
                  Please <a href={% url 'login' %}>authenticate</a> using the new account.
                </p>  

              {% else %}

                <div class="card-body">

                    <div class="login-input-div">
                      <div class="px-md-1">
                        <div class="form-group">
                          <label>Username</label>
                          {{ form.username }}
                        </div>
                      </div>
                    </div>
                    <span class="text-danger">{{ form.username.errors }}</span>

                    <div class="login-input-div">
                      <div class="px-md-1">
                        <div class="form-group">
                          <label>Email</label>
                          {{ form.email }}
                        </div>
                      </div>
                    </div>
                    <span class="text-danger">{{ form.email.errors }}</span>

                    <div class="login-input-div">
                      <div class="px-md-1">
                        <div class="form-group">
                          <label>Password</label>
                          {{ form.password1 }}
                        </div>
                      </div>
                    </div>
                    <span class="text-danger">{{ form.password1.errors }}</span>
                    
                    <div class="login-input-div">
                        <div class="px-md-1">
                            <div class="form-group">
                            <label>Password Check</label>
                            {{ form.password2 }}
                            </div>
                        </div>
                    </div>
                    <span class="text-danger">{{ form.password2.errors }}</span>

                </div>
                <div class="card-footer">
                  <button type="submit" name="register" class="btn btn-fill">Register</button>
                  &nbsp; &nbsp;
                  Have an account? <a href="{% url 'login' %}" class="text-primary">Login</a>
                </div>

              {% endif %} 

              </form>

            </div>
          </div>
      </div>


{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

templates/home/dashboard.html
{% extends "layouts/base.html" %}

{% block title %} Dashboard {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

<div class="row">
  <div class="col-md-12">
      <div class="card card-profile">
          <div class="card-body">
              <h2 class="card-title">
                History
              </h2>

              <table class="table">
                <thead>
                  <tr>
                    <th class = "table-title" scope="col">#</th>
                    <th class = "table-title" scope="col">dates</th>
                    <th class = "table-title" scope="col">image</th>
                    <th class = "table-title" scope="col">recognized</th>
                  </tr>
                </thead>
                <tbody>
                    {% for result in results %}
                        <tr class = "data-class" data-toggle="modal" data-target="#myModal" 
                            data-src="{{result.img_path}}" 
                            data-result="{{result.recognized}}"
                            data-udi="{{result.udi}}">
                          <th scope="row">{{result.id}}</th>
                          <td class = "table-rows" >{{result.dates}}</td>
                          <td class = "table-rows" >{{result.img_path}}</td>
                            {% if result.recognized %}
                            <td class = "table-rows" >
                                <div class="result-success rounded-circle">
                                </div>
                            </td>
                            {% else %}
                            <td class = "table-rows" >
                                <div class="result-fail rounded-circle">
                                </div>
                            </td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                </tbody>
              </table>
          </div>
      </div>
  </div>
</div>

<!-- Modal -->
<div id = "myModal" class="modal fade" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-xl">
    <div class="modal-content">
      <div class="modal-header">
        <h3 class="modal-title" id="exampleModalLabel">Detailed description</h3>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <table class="table">
            <thead>
              <tr>
                <th class = "table-title" scope="col">udi value</th>
                <th class = "table-title" scope="col">result</th>
              </tr>
            </thead>
            <tbody>
                <td id="udi"></td>
                <td id="result"></td>
            </tbody>
          </table>
        <img id="my_image" />
        </src>
      </div>
      <div class="modal-footer justify-content-md-end">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}
<script>
$(document).on("click", ".data-class", function () {
 var imgsrc = $(this).data('src');
 var result = $(this).data('result');
 var udi = $(this).data('udi');

 console.log(result)
 console.log(udi)
 $('#my_image').attr('src',imgsrc);
 $('#udi').html(udi);
 if(result == "True"){
    $('#result').html(
        `
        <div class="result-success rounded-circle">
        </div>
        `
    );
 }else{
    $('#result').html(
        `
        <div class="result-fail rounded-circle">
        </div>
        `
    );

 }
});
</script>
{% endblock javascripts %}

templates/home/index.html
{% extends "layouts/base.html" %}

{% block title %} Dashboard {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

<div class="row">
  <div class="col-md-12">
      <div class="card card-profile">
        <form role="form" method="post" action="" enctype="multipart/form-data">
          {% csrf_token %} 
          <div class="card-body">
            
            <div class="index-title">
              <h4 class="card-title">
                  Input Your UDI Barcode Image! 
              </h4>
              <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                <button onclick="sendImage()" type = "submit" class="btn mt-3">Click me</button>
              </div>
            </div>
            
              <div class="container col-md-12">
                <div class="select-image">
                    <label for="Image" class="form-label">Select Image Please</label>
                    <input class="form-control" type="file" required id="id_file" name="file" onchange="preview()">
                </div>

                <table class="table">
                  <thead>
                    <tr>
                      <th class = "table-title" scope="col">udi value</th>
                      <th class = "table-title" scope="col">result</th>
                    </tr>
                  </thead>
                  <tbody>
                      <td id="udi">{{data}}</td>
                      <td id="result">{{msg}}</td>
                  </tbody>
                </table>
                <img id="frame" src="" class="img-fluid" />
            </div>
          </div>
        </form>
      </div>
  </div>
</div>
{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}
<script>
  function preview() {
      document.getElementById('udi').innerHTML = ""
      document.getElementById('result').innerHTML = ""
      frame.src = URL.createObjectURL(event.target.files[0]);
  }
  function sendImage() {
      if(document.getElementById('id_file').value != ""){
        frame.src = "/static/assets/img/loading.gif";
      }else{
        alert("Input Image First!!")
      }
  }
</script>
{% endblock javascripts %}

templates/home/page-blank.html
{% extends "layouts/base.html" %}

{% block title %} Page Blank {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="row">
        <div class="col-md-12">
            <div class="card card-profile">
                <div class="card-body">
                    <h6 class="card-category text-gray">Page Blank</h6>
                    <h4 class="card-title">
                        Add your content 
                    </h4>
                    <a href="/" class="btn btn-primary btn-round">Home</a>
                </div>
            </div>
        </div>
    </div>
    
{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

templates/home/page-user.html
{% extends "layouts/base.html" %}

{% block title %} Page User {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

<div class="row">
  <div class="col-md-8">
    <div class="card">
      <div class="card-header">
        <h5 class="title">Edit Profile</h5>
      </div>
      <div class="card-body">
        <form>
          <div class="row">
            <div class="col-md-5 pr-md-1">
              <div class="form-group">
                <label>UserID (disabled)</label>
                <input type="text" class="form-control" disabled="" value="{{ request.user.id }}">
              </div>
            </div>
            <div class="col-md-3 px-md-1">
              <div class="form-group">
                <label>Username</label>
                <input type="text" class="form-control" value="{{ request.user.username }}">
              </div>
            </div>
            <div class="col-md-4 pl-md-1">
              <div class="form-group">
                <label for="exampleInputEmail1">Email address</label>
                <input type="email" class="form-control" value="{{ request.user.email }}">
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-6 pr-md-1">
              <div class="form-group">
                <label>First Name</label>
                <input type="text" class="form-control" placeholder="Company" value="Mike">
              </div>
            </div>
            <div class="col-md-6 pl-md-1">
              <div class="form-group">
                <label>Last Name</label>
                <input type="text" class="form-control" placeholder="Last Name" value="Andrew">
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12">
              <div class="form-group">
                <label>Address</label>
                <input type="text" class="form-control" placeholder="Home Address" value="Bld Mihail Kogalniceanu, nr. 8 Bl 1, Sc 1, Ap 09">
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-4 pr-md-1">
              <div class="form-group">
                <label>City</label>
                <input type="text" class="form-control" placeholder="City" value="Mike">
              </div>
            </div>
            <div class="col-md-4 px-md-1">
              <div class="form-group">
                <label>Country</label>
                <input type="text" class="form-control" placeholder="Country" value="Andrew">
              </div>
            </div>
            <div class="col-md-4 pl-md-1">
              <div class="form-group">
                <label>Postal Code</label>
                <input type="number" class="form-control" placeholder="ZIP Code">
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-8">
              <div class="form-group">
                <label>About Me</label>
                <textarea rows="4" cols="80" class="form-control" placeholder="Here can be your description" value="Mike">Lamborghini Mercy, Your chick she so thirsty, I'm in that two seat Lambo.</textarea>
              </div>
            </div>
          </div>
        </form>
      </div>
      <div class="card-footer">
        <button type="submit" class="btn btn-fill">Save</button>
      </div>
    </div>
  </div>
</div>


{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

templates/includes/footer.html
      <footer class="footer">
        <div class="container-fluid">
          <ul class="nav">
            <li class="nav-item">
              <a target="_blank" rel="noopener noreferrer"
                 href="https://appseed.us/admin-dashboards/django-dashboard-black" class="nav-link">
                Django Dashboard Black
              </a>
            </li>
          </ul>
          <div class="copyright">
            &copy; <a target="_blank" rel="sponsored noopener noreferrer" 
                      href="https://bit.ly/3fKQZaL">Creative-Tim</a> 
            - coded by <a target="_blank" rel="noopener noreferrer" href="https://appseed.us">AppSeed</a>
          </div>
        </div>
      </footer>
      

templates/includes/navigation.html
      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-absolute navbar-transparent">
        <div class="container-fluid">
          <div class="navbar-wrapper">
            <div class="navbar-toggle d-inline">
              <button type="button" class="navbar-toggler">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
              </button>
            </div>
            <a class="navbar-brand" href="javascript:void(0)">
              <img class = "logo-img" id = "logo-img" src="/static/logo.png" alt="Profile Photo"> 
            </a>
          </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-bar navbar-kebab"></span>
            <span class="navbar-toggler-bar navbar-kebab"></span>
            <span class="navbar-toggler-bar navbar-kebab"></span>
          </button>
          <div class="collapse navbar-collapse" id="navigation">

            <ul class="navbar-nav ml-auto">

              {% if request.user.is_authenticated %}
              <li class="dropdown nav-item">
                <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
                  <div class="photo">  
                    <img src="/static/assets/img/anime3.png" alt="Profile Photo"> 
                  </div>
                  <b class="caret d-none d-lg-block d-xl-block"></b>
                </a>
                <ul class="dropdown-menu dropdown-navbar">
                  <li class="nav-link"><a href="{% url 'logout' %}" class="nav-item dropdown-item">Log out</a></li>
                </ul>
              </li>
              {% else %}
              <li class="dropdown nav-item">
                <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
                  <div class="photo">  
                    <img src="/static/assets/img/default-avatar.png" alt="Profile Photo">
                  </div>
                  <b class="caret d-none d-lg-block d-xl-block"></b>
                </a>
                <ul class="dropdown-menu dropdown-navbar">
                  <li class="nav-link"><a href="{% url 'login' %}" class="nav-item dropdown-item">Log In</a></li>
                </ul>
              </li>
              {% endif %} 

            </ul>

          </div>
        </div>
      </nav>
      <div class="modal modal-search fade" id="searchModal" tabindex="-1" role="dialog" aria-labelledby="searchModal" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <input type="text" class="form-control" id="inlineFormInputGroup" placeholder="SEARCH">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <i class="tim-icons icon-simple-remove"></i>
              </button>
            </div>
          </div>
        </div>
      </div>
      <!-- End Navbar -->

templates/includes/scripts.html
  <!--   Core JS Files   -->
  <script src="/static/assets/js/core/jquery.min.js"></script>
  <script src="/static/assets/js/core/popper.min.js"></script>
  <script src="/static/assets/js/core/bootstrap.min.js"></script>
  <script src="/static/assets/js/plugins/perfect-scrollbar.jquery.min.js"></script>
  <!-- Chart JS -->
  <script src="/static/assets/js/plugins/chartjs.min.js"></script>
  <!--  Notifications Plugin    -->
  <script src="/static/assets/js/plugins/bootstrap-notify.js"></script>
  <!-- Control Center for Black Dashboard: parallax effects, scripts for the example pages etc -->
  <script src="/static/assets/js/black-dashboard.min.js?v=1.0.0"></script><!-- Black Dashboard DEMO methods, don't include it in your project! -->
  <script src="/static/assets/demo/demo.js"></script>
  

templates/includes/sidebar.html
    <div class="sidebar" data = "blue">
      <div class="sidebar-wrapper">
        <div class="logo">
          <a href="/" class="simple-text logo-mini">
            UDI
          </a>
          <a href="/" class="simple-text logo-normal">
            Home
          </a>
        </div>

        <ul class="nav">
        {% if request.user.is_authenticated %}

          <li class="{% if 'index' in segment %} active {% endif %}">
            <a href="/">
              <i class="tim-icons icon-chart-pie-36"></i>
              <p>Recognition</p>
            </a>
          </li>
          <li class="{% if 'dashboard' in segment %} active {% endif %}">
            <a href="/dashboard">
              <i class="tim-icons icon-atom"></i>
              <p>My Dashboard</p>
            </a>
          </li>
          <li class="{% if 'user' in segment %} active {% endif %}">
            <a href="/user">
              <i class="tim-icons icon-pin"></i>
              <p>My Page</p>
            </a>
          </li>
          {% endif %}
                    
        </ul>
        
      </div>
    </div>